export const REASONS = [
  {
    id: "G3-01",
    text: "저 수학 필요 없는데요.",
    category: "불필요 선언",
    image: "./assets/reasons/g3-01-math-not-needed.webp",
    alt: "수학책과 포물선 밧줄에 발목이 잡힌 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-02",
    text: "저 내신 필요 없는데요.",
    category: "성적 계단",
    image: "./assets/reasons/g3-02-grades-not-needed.webp",
    alt: "성적표 모양의 빈 타일 계단을 뛰어넘으려는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-03",
    text: "저 수능 필요 없는데요.",
    category: "시험 궤도",
    image: "./assets/reasons/g3-03-csat-not-needed.webp",
    alt: "빈 시험지 패널이 궤도를 돌고 파란 띠가 허리를 감싼 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-05",
    text: "저 수시 붙었는데요.",
    category: "입시 완료",
    image: "./assets/reasons/g3-05-early-admission.webp",
    alt: "작은 메달을 든 학생 피규어가 거대한 기자회견 연단에 선 모습",
    enabled: true,
  },
  {
    id: "G3-07",
    text: "저 최저 맞췄는데요.",
    category: "조기 은퇴",
    image: "./assets/reasons/g3-07-minimum-met.webp",
    alt: "작은 왕관을 쓰고 은퇴 포즈를 취한 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-08",
    text: "저 면접만 남았는데요.",
    category: "면접 과준비",
    image: "./assets/reasons/g3-08-only-interview-left.webp",
    alt: "거대한 마이크와 정장 가방을 함께 끄는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-10",
    text: "저 논술 준비해야 되는데요.",
    category: "원고지 방패",
    image: "./assets/reasons/g3-10-essay-prep.webp",
    alt: "빈 원고지 롤이 팔과 다리에 감긴 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-13",
    text: "저 재수할 건데요.",
    category: "다음 시즌",
    image: "./assets/reasons/g3-13-repeat-next-year.webp",
    alt: "책을 미래로 향하는 투명 캡슐에 넣는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-21",
    text: "저 이미 진로 정했는데요.",
    category: "한 길 고수",
    image: "./assets/reasons/g3-21-career-decided.webp",
    alt: "미로 지도 위에서 하나의 파란 길만 지키는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-25",
    text: "저 이거 시험에 안 나오잖아요.",
    category: "조명 밖 선언",
    image: "./assets/reasons/g3-25-not-on-test.webp",
    alt: "스포트라이트 밖으로 책을 밀어내지만 그림자는 원 안에 남은 장면",
    enabled: true,
  },
  {
    id: "G3-26",
    text: "저 졸업만 하면 되는데요.",
    category: "너무 이른 결승",
    image: "./assets/reasons/g3-26-graduation-only.webp",
    alt: "멀리 있는 결승선 앞에서 졸업모를 쓰고 쉬는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-27",
    text: "저 출석만 하면 되는 거 아니에요?",
    category: "도장 트로피",
    image: "./assets/reasons/g3-27-attendance-only.webp",
    alt: "거대한 빈 원형 도장을 트로피처럼 끌어안은 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-34",
    text: "저 원서 다 썼는데요.",
    category: "종이비행기",
    image: "./assets/reasons/g3-34-applications-sent.webp",
    alt: "빈 봉투 종이비행기를 날리며 마지막 봉투를 손끝에 붙인 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-35",
    text: "저 합격 발표만 기다리면 되는데요.",
    category: "대기 캠핑",
    image: "./assets/reasons/g3-35-waiting-results.webp",
    alt: "거대한 빈 알림 벨 앞 캠핑 의자에 앉아 기다리는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-38",
    text: "저 오늘만 쉴게요.",
    category: "미루기",
    image: "./assets/reasons/g3-38-today-only.webp",
    alt: "소파에 앉은 학생 피규어 옆에서 빈 달력 종이를 무한 출력하는 기계",
    enabled: true,
  },
  {
    id: "G3-52",
    text: "요즘 AI가 다 해주는데요.",
    category: "외주 진화",
    image: "./assets/reasons/g3-52-ai-does-it.webp",
    alt: "로봇이 책상에서 공부하고 학생 피규어는 큰 의자에서 리모컨을 든 모습",
    enabled: true,
  },
  {
    id: "G3-04",
    text: "저 대학 안 갈 건데요.",
    category: "캠퍼스 로켓",
    image: "./assets/reasons/g3-04-no-college.webp",
    alt: "책가방을 끌고 떠나는 캠퍼스 모양 로켓을 바라보는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-06",
    text: "저 최저 없는데요.",
    category: "낮은 문턱",
    image: "./assets/reasons/g3-06-no-minimum.webp",
    alt: "낮은 문을 지난 뒤 끝없는 복도를 바라보는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-09",
    text: "저 실기만 하면 되는데요.",
    category: "장비 과적",
    image: "./assets/reasons/g3-09-practical-only.webp",
    alt: "거대한 실기 장비 가방이 문틀에 걸린 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-11",
    text: "저 정시 안 할 건데요.",
    category: "기차 외면",
    image: "./assets/reasons/g3-11-no-regular-admission.webp",
    alt: "지나가는 파란 열차를 등지고 캠핑 의자에 앉은 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-12",
    text: "저 정시 할 거라 내신 필요 없는데요.",
    category: "선로 갈아타기",
    image: "./assets/reasons/g3-12-regular-not-grades.webp",
    alt: "두 선로 사이를 뛰어넘지만 빈 성적표 타일이 발목에 걸린 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-15",
    text: "저 취업할 건데요.",
    category: "취업 돌진",
    image: "./assets/reasons/g3-15-employment.webp",
    alt: "빈 종이 갑옷을 입고 문으로 달리지만 가방이 문턱에 걸린 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-18",
    text: "저 학과에서 수학 안 쓰는데요.",
    category: "도구 상자",
    image: "./assets/reasons/g3-18-major-no-math.webp",
    alt: "도형과 삼각자가 튀어나오는 파란 도구 상자를 닫으려는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-20",
    text: "저 예체능인데요.",
    category: "과대 방패",
    image: "./assets/reasons/g3-20-arts-athletics.webp",
    alt: "거대한 팔레트를 방패처럼 들고 도형을 피하는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-23",
    text: "저 대학 가서 다시 배우면 되잖아요.",
    category: "미래 위임",
    image: "./assets/reasons/g3-23-learn-in-college.webp",
    alt: "먼 미래의 구름 플랫폼을 향해 책을 발사하는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-29",
    text: "저 성적 이미 나왔잖아요.",
    category: "봉인 금고",
    image: "./assets/reasons/g3-29-grades-already-out.webp",
    alt: "빈 격자 카드가 든 거대한 금고에 등을 돌리고 열쇠를 던지는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-31",
    text: "저 지금 시작하기엔 너무 늦었는데요.",
    category: "늦은 출발",
    image: "./assets/reasons/g3-31-too-late-to-start.webp",
    alt: "거대한 모래시계 옆 출발 블록에서 망설이는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-39",
    text: "저 다음 시간부터 할게요.",
    category: "다음 시간",
    image: "./assets/reasons/g3-39-next-class.webp",
    alt: "빈 패널을 계속 넘기는 기계 옆에서 다음을 기다리는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-40",
    text: "저 집에서 할 건데요.",
    category: "책상 이사",
    image: "./assets/reasons/g3-40-study-at-home.webp",
    alt: "거대한 파란 공부 책상을 들고 문을 통과하려는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-43",
    text: "저 문제집 이미 다 풀었는데요.",
    category: "문제집 탑",
    image: "./assets/reasons/g3-43-workbook-finished.webp",
    alt: "파란 리본으로 묶인 거대한 빈 문제집 탑에 기대 선 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-45",
    text: "저 모르는 것만 질문하면 안 돼요?",
    category: "한 칸만",
    image: "./assets/reasons/g3-45-ask-only-unknown.webp",
    alt: "큰 확대경으로 책의 작은 빈 칸 하나만 살피는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-50",
    text: "저 원서 찾아봐야 돼요.",
    category: "원서 탐험",
    image: "./assets/reasons/g3-50-find-applications.webp",
    alt: "빈 서랍 벽을 쌍안경으로 살피는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-14",
    text: "저 군대 갔다 와서 공부할 건데요.",
    category: "먼 미래 배낭",
    image: "./assets/reasons/g3-14-study-after-military.webp",
    alt: "책을 얹은 거대한 여행 배낭 옆에서 기다리는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-16",
    text: "저 공무원 준비할 건데요.",
    category: "서류 방패",
    image: "./assets/reasons/g3-16-civil-service.webp",
    alt: "두꺼운 빈 서류 더미로 파란 책을 막는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-17",
    text: "저 전문대 갈 건데요.",
    category: "급행 출발",
    image: "./assets/reasons/g3-17-junior-college.webp",
    alt: "큰 여행 가방과 도구 상자를 올린 작은 파란 열차에 선 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-19",
    text: "저 문과인데요.",
    category: "책 성벽",
    image: "./assets/reasons/g3-19-humanities.webp",
    alt: "책으로 만든 작은 성벽 뒤에서 빈 버튼의 파란 계산기 공을 피하는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-22",
    text: "저 하고 싶은 게 따로 있는데요.",
    category: "꿈의 궤도",
    image: "./assets/reasons/g3-22-other-dream.webp",
    alt: "취미 물체가 도는 주황 행성을 바라보고 파란 책에 발목이 묶인 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-28",
    text: "저 수행평가 다 끝났는데요.",
    category: "도장 휴가",
    image: "./assets/reasons/g3-28-performance-done.webp",
    alt: "거대한 주황 도장과 빈 종이 더미 옆에서 편히 쉬는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-30",
    text: "저 지금 해도 성적 안 오르는데요.",
    category: "사다리 관망",
    image: "./assets/reasons/g3-30-grades-wont-rise.webp",
    alt: "파란 접이식 사다리와 높은 책 플랫폼을 올려다보는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-32",
    text: "저 3년 동안 했는데 이제 좀 쉬면 안 돼요?",
    category: "3년치 배낭",
    image: "./assets/reasons/g3-32-three-years-rest.webp",
    alt: "거대한 책 배낭 앞 의자에서 빈 항복기를 든 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-24",
    text: "저 필요한 것만 공부하면 되잖아요.",
    category: "지식 뷔페",
    image: "./assets/reasons/g3-24-study-only-needed.webp",
    alt: "파란 책 벽에서 작은 책 한 권만 집게로 골라 카트에 담는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-33",
    text: "저 수능 끝났는데요.",
    category: "종료 축포",
    image: "./assets/reasons/g3-33-csat-over.webp",
    alt: "빈 시험지가 흩날리는 가운데 파란 단상 위에서 만세 하는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-36",
    text: "저 어차피 떨어질 것 같은데요.",
    category: "조기 낙하산",
    image: "./assets/reasons/g3-36-probably-fail.webp",
    alt: "낮은 계단 위에서 빈 봉투에 작은 낙하산을 다는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-37",
    text: "저 어차피 붙을 것 같은데요.",
    category: "종이 왕관",
    image: "./assets/reasons/g3-37-probably-pass.webp",
    alt: "눈을 가리는 커다란 빈 종이 왕관을 쓴 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-41",
    text: "저 인강으로 할 건데요.",
    category: "빈 화면 강의",
    image: "./assets/reasons/g3-41-online-lecture.webp",
    alt: "빈 화면 세 장을 향해 빈백에 기대 누운 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-42",
    text: "저 혼자 하는 게 더 잘돼요.",
    category: "혼공 미로",
    image: "./assets/reasons/g3-42-study-alone.webp",
    alt: "파란 책으로 만든 미로 한가운데에서 책을 든 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-44",
    text: "저 이거 아는 내용인데요.",
    category: "아는 척 도장",
    image: "./assets/reasons/g3-44-already-know.webp",
    alt: "내려오는 거대한 빈 파란 도장 앞에서 손사래 치는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-46",
    text: "저 지금 다른 과목이 더 급한데요.",
    category: "우선순위 판넬",
    image: "./assets/reasons/g3-46-other-subject-urgent.webp",
    alt: "경고등이 켜진 책을 두고 주황 화살표를 돌리는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-47",
    text: "저 영어 단어 외워야 되는데요.",
    category: "카드 폭풍",
    image: "./assets/reasons/g3-47-english-words.webp",
    alt: "빈 카드 폭풍 속에서 책에 발목이 묶인 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-48",
    text: "저 면접 준비해야 돼요.",
    category: "악수 면접",
    image: "./assets/reasons/g3-48-interview-prep.webp",
    alt: "큰 책 거울 앞 흰 손 모형과 악수 연습을 하는 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-49",
    text: "저 자소서 써야 돼요.",
    category: "종이 리본",
    image: "./assets/reasons/g3-49-personal-statement.webp",
    alt: "빈 종이 리본 속에서 한 장을 치켜든 학생 피규어",
    enabled: true,
  },
  {
    id: "G3-51",
    text: "계산은 계산기가 하는데요.",
    category: "계산기 팀장",
    image: "./assets/reasons/g3-51-calculator-does-it.webp",
    alt: "파란 계산기 로봇에게 큰 책을 맡기고 의자에서 지시하는 학생 피규어",
    enabled: true,
  },
];

export const approvedReasons = () => REASONS.filter((reason) => reason.enabled);
